---
name: Self-Test

on:
  push: ~

env:
  CACHE_REGISTRY: ghcr.io
  CACHE_IMAGE: ${{ github.repository }}
  CACHE_TAG: release-cache

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CACHE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create something to cache
        run: |
          mkdir -p target \
            && echo 'hello, target!' > target/payload.txt
          mkdir -p /usr/share/something \
            && echo 'hello, /usr/share/something!' > /usr/share/something/payload.txt

          ls -la target \
            && cat target/payload.txt
          ls -la /usr/share/something \
            && cat /usr/share/something/payload.txt

      - name: Save cache
        id: save_cache
        uses: ./save
        with:
          paths: "${{ github.workspace }}/target /usr/share/something"
          registry: ${{ env.CACHE_REGISTRY }}
          image: ${{ env.CACHE_IMAGE }}
          tag: ${{ env.CACHE_TAG }}

      - name: Print cache
        run: |
          echo "Cache saved as: ${{ steps.save_cache.outputs.image-name }}"

      - name: Clear demo files
        run: |
          rm -rf target /usr/share/something

      - name: Restore cache
        uses: ./restore
        with:
          registry: ${{ env.CACHE_REGISTRY }}
          image: ${{ env.CACHE_IMAGE }}
          tag: ${{ env.CACHE_TAG }}

      - name: Assert cache
        run: |
          ls -la target \
            && cat target/payload.txt
          ls -la /usr/share/something \
            && cat /usr/share/something/payload.txt
